apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-controller
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-cors: "true" 
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://web.careerflow.shop"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - careerflow.shop
    - www.careerflow.shop
    secretName: careerflow-tls
  rules:
  - host: careerflow.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: careerflow-client
            port:
              number: 80
      - path: /api/chat
        pathType: Prefix
        backend:
          service:
            name: careerflow-chat
            port:
              number: 3005
      - path: /api/connect
        pathType: Exact
        backend:
          service:
            name: careerflow-chat
            port:
              number: 3005
      - path: /socket.io  
        pathType: Prefix
        backend:
          service:
            name: careerflow-chat
            port:
              number: 3005
      - path: /api/users/user
        pathType: Prefix
        backend:
          service:
            name: careerflow-user
            port:
              number: 3002
      - path: /api/users/admin
        pathType: Prefix
        backend:
          service:
            name: careerflow-user
            port:
              number: 3002
      - path: /api/users/company
        pathType: Prefix
        backend:
          service:
            name: careerflow-company
            port:
              number: 3003
