apiVersion: apps/v1
kind: Deployment
metadata:
  name: careerflow-company
spec:
  replicas: 1
  selector:
    matchLabels:
      app: careerflow-company
  template:
    metadata:
      labels:
        app: careerflow-company
    spec:
      containers:
      - name: careerflow-company
        image: jabirhussainat/careerflow-company:0.1.2
        ports:
        - containerPort: 3003
        envFrom:
        - configMapRef:
            name: company-config  # Name of the ConfigMap
  # Add dependsOn field to specify Kafka deployment dependency
  # This requires Kubernetes API version 1.21 or later
  # dependsOn:
  # - name: kafka
  #   condition: Ready
---
apiVersion: v1
kind: Service
metadata:
  name: careerflow-company
spec:
  selector:
    app: careerflow-company
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
