import { 
    createNewUser,
    saveOtp,
    verifyOtp ,
    updateFormData ,
    fetchCompanies ,
    updateApprovel ,
    addJobInCompany ,
    fetchComJobInCompany ,
    editJobInCompany ,
    changeJobStatus ,
    fetchJobs ,
    fetchJob ,
    getChartData ,
    addCategory ,
    getPreferedJobs ,
    fetchCategories ,
    getJobsAndApplicantsCount ,
    findJobs,
    jobApply ,
    getMyJobApplications ,
    changeJobApplicationStatus
 } from "./companyRepo"; 

export default {
    createNewUser,
    saveOtp ,
    verifyOtp ,
    updateFormData,
    fetchCompanies ,
    updateApprovel,
    addJobInCompany ,
    fetchComJobInCompany ,
    editJobInCompany ,
    changeJobStatus ,
    fetchJobs ,
    fetchJob ,
    getChartData ,
    addCategory ,
    fetchCategories ,
    findJobs ,
    getJobsAndApplicantsCount ,
    jobApply ,
    getPreferedJobs ,
    getMyJobApplications ,
    changeJobApplicationStatus

}