apiVersion: v1
kind: ConfigMap
metadata:
  name: company-config
data:
  FRONT_END_URL: "http://careerflow-frontend-repo.onrender.com
  EMAIL: "carcareecom@gmail.com"
  PASSWORD: "cwaw orvq waai jdla"
  HASH_SALT: "10"
  JWT_SECRET: "careerFlow"
  NODE_ENV: "production"
  MONG_ODB_URL: "mongodb+srv://jabirmhd6786:SBIYRiTREyA1tZDa@cluster0.odrintd.mongodb.net/company-service?retryWrites=true&w=majority&appName=Cluster0"
  PORT: "3003"
  KAFKA_BOOTSTRAP_SERVER: "pkc-41p56.asia-south1.gcp.confluent.cloud:9092"
  KAFKA_CLIENT_ID: "company-client"
  KAFKA_USERNAME: "F4NUXIJ3IZADPFSO"
  KAFKA_PASSWORD: "DrOln1QRgJAUi1ruYxJBTZbH7H+ArJTbvrfA4lHmXovB9eIzABND/WDN2DZ4ji2u"
