name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and tag Docker images
        run: |
          cd services/user-service && docker build -t careerflow-user:0.0.4 . &&
          cd ../chat-service && docker build -t careerflow-chat:0.0.4 . &&
          cd ../company-service && docker build -t careerflow-company:0.0.4 . &&
          cd ../../client && docker build -t careerflow-client:0.0.4 . &&
          docker tag careerflow-user:0.0.4 jabirhussainat/careerflow-user:0.0.4 &&
          docker tag careerflow-chat:0.0.4 jabirhussainat/careerflow-chat:0.0.4 &&
          docker tag careerflow-company:0.0.4 jabirhussainat/careerflow-company:0.0.4 &&
          docker tag careerflow-client:0.0.4 jabirhussainat/careerflow-client:0.0.4 &&
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker images to registry
        run: |
          docker push jabirhussainat/careerflow-user:0.0.4 &&
          docker push jabirhussainat/careerflow-chat:0.0.4 && 
          docker push jabirhussainat/careerflow-company:0.0.4 &&
          docker push jabirhussainat/careerflow-client:0.0.4
      - name: Setup kubectl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Configure kubectl
        run: doctl kubernetes cluster kubeconfig save k8s-1-29-1-do-0-blr1-1711538524447
      - name: Restart deployments
        run: |
          kubectl rollout restart deployment careerflow-client
          kubectl rollout restart deployment careerflow-chat
          kubectl rollout restart deployment careerflow-company
          kubectl rollout restart deployment careerflow-user
